# Copyright (c) 2026 Ednei Monteiro. Licensed under the MIT License.
# See LICENSE and DISCLAIMER.md in the project root for details.
apiVersion: v1
kind: Namespace
metadata:
  name: upload
  labels:
    app.kubernetes.io/part-of: upload
